# Generated by Django 5.0.1 on 2024-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_exhibit_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='exhibit_images/')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='playtypeCognitive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='playtypeCommunication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='playtypePhysical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='playtypeSensory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='playtypeSocialEmotional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
